source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

target 'WildFireChat' do
    
    pod 'WFChatClient', :path => '../wfclient'
    pod 'WFChatUIKit', :path => '../wfuikit'
    
end
